;[GROUPX]	where X is the scenario just played.
;			List of all regions conquered since last scenario.
;MER	=	
;HAR 	=	
;SAR	=	
;			attack region, arrow#, x, y
;REG1	=	
;REG2	=
;REG3	=
;max text line is [------------------------------------------]
; at times, territories will be repeated that a house already has, this
; will give more time to read the text.

[GROUP1]
MER	=	13, 7, 20, 14, 21, 22
HAR 	=	19, 27, 26, 25, 24, 23
SAR	=	6, 5, 4, 10, 3, 9
REG1	=	15, 8, 145, 121
REG2	=	16, 1, 183, 109
REG3	=	17, 2, 218, 90
ENGTXT19	=  Harkonnen took the best land.
ENGTXT13	=  House Mercenary is nearby.
ENGTXT6	=  Sardaukar are a threat.
FRETXT19 	=  Les Harkonnen ont capturÇ la meilleure terre.
FRETXT13 	=  Les Mercenary sont tout präs.
FRETXT6 	=  Les Sardaukar reprÇsentent une menace.
GERTXT19 	=  Harkonnen nahmen das beste Land an sich.
GERTXT13 	=  Mercenary befinden sich ganz in der NÑhe.
GERTXT 6  	=  Sardaukar stellen eine Bedrohung dar.

[GROUP2]
HAR 	=	15, 16, 17, 
MER	=	1, 2, 8
SAR	=	11, 12, 18
REG1	=	14, 8, 88, 96 
REG2	=	22, 7, 104, 120
REG3	=	8, 2, 119, 89
ENGTXT15	=  Harkonnen advanced without a challenge.
ENGTXT11	=  The Sardaukar drew closer.
ENGTXT1	=  The Mercenary spread too thin.
FRETXT15 	=  Les Harkonnen ont avancÇ sans problÇme.
FRETXT11 	=  Les Sardaukar se sont rapprochÇs.
FRETXT1	=  Les Mercenary se sont trop dÇployÇs.
GERTXT15 	=  Harkonnen sind ohne Kampfansage vorgerÅckt.
GERTXT11 	=  Sardaukar sind nÑher gerÅckt.
GERTXT1 	=  Mercenary-Truppen waren unterbesetzt.

[GROUP3]
HAR	=	8, 14, 22
SAR	=	2
REG1	=	13, 8, 22, 91
REG2	=	20, 7, 33, 107
REG3	=	21, 7, 64, 120
ENGTXT8 	= All attacks were directed at the Mercenary.
FRETXT8 	= Attaques toutes dirigÇes contre Mercenary.
GERTXT8 	= Alle Angriffe waren gegen Mercenary.

[GROUP4]
HAR	=	21, 20, 13
MER 	=	2, 3
REG1	=	11, 3, 226, 71
REG2	=	18, 1, 272, 96
REG3	=	12, 1, 292, 64
ENGTXT21	=  Harkonnen took advantage of the Mercenary...
ENGTXT2	=  ...while they were fighting the Sardaukar.
FRETXT21 	=  Harkonnen ont profitÇ du fait qu'Mercenary...
FRETXT2 	=  ...combattaient Sardaukar.
GERTXT21 	=  Harkonnen haben Mercenary ÅberwÑltigt...
GERTXT2 	=  ...als sie gerade Sardaukar bekÑmpften.

[GROUP5]
HAR	=	18, 11, 12
REG1	=	1, 4, 0, 24, 
REG2	=	7, 1, 49, 86
REG3	=	2, 2, 84, 60
ENGTXT18	= The Sardaukar had to be turned back.
FRETXT18     	= Il a fallu repousser les Sardaukar.
GERTXT18     	= Sardaukar mu·ten abgewehrt werden.

[GROUP6]
HAR	=	7, 1, 2
REG1	=	10, 1, 208, 64 
REG2	=	5, 3, 240, 56 
REG3	=	6, 2, 288, 32
ENGTXT7  	=  Harkonnen killed off most of the Mercenary.
FRETXT7  	=  Les Harkonnen ont tuÇ la plupart des Mercenary.
GERTXT7  	=  Harkonnen haben fast alle Mercenary vernichtet.

[GROUP7]
HAR	=	6, 5, 10
REG1	=	3, 2, 120, 55 
REG2	=	9, 3, 136, 72
ENGTXT6	=  Harkonnen conquered more Sardaukar land.
FRETXT6  	=  Harkonnen prennent terres aux Sardaukar.
GERTXT6  	=  Harkonnen erobern mehr Sardaukar-Gebiet.

[GROUP8]
HAR 	=	3, 9
ATR	=	4
REG1	=	4, 3, 154, 32 
REG2	=	4, 2, 168, 48 
REG3	=	4, 8, 199, 37
ENGTXT3	=  Soon Harkonnen will control all of Dune.
FRETXT3 	=  Bientìt, les Harkonnen rägneront sur Dune.
GERTXT3  	=  Bald beherrschen Harkonnen ganz Dune.

[PIECES]
1	=	0, 	0
2	=	55, 	0
3	=	97, 	0
4	=	145,	0
5	=	211,	0
6	=	247,	0
7	=	0,	9
8	=	71,	38
9	=	133,	31
10	=	173,	16
11	=	220,	22
12	=	264,	16
13	=	0,	41
14	=	21,	46
15	=	87,	70
16	=	148,	45
17	=	186,	45
18	=	243,	47
19	=	280,	47
20	=	0,	82
21	=	23,	91
22	=	59,	86
23	=	133,	92
24	=	172,	90
25	=	195,	70
26	=	216,	98
27	=	249,	77 

[INFO]
TOTAL REGIONS	= 	27
